### PR TITLE
Change IP fields to VARCHAR(45), fixes #36

### LINKED ISSUE #36: Database error with IPv6 addresses
When IPv6 addresses pass through to the ABF extension, you will see a database error on the second login attempt, onviously caused by the fact that the IP address gets cut off in the `IP` column (defined as `VARCHAR 16`).

> Symphony Fatal Database Error: Duplicate entry '2003:63:2a15:376' for key 'PRIMARY'
>
> An error occurred while attempting to execute the following query
>
> INSERT INTO sym_anti_brute_force ( `IP`, `RawIP`, `LastAttempt`, `Username`, `FailedCount`, `UA`, `Source`, `Hash` ) VALUES ( '2003:63:2a15:3767:358f:480e:202d:6883', '2003:63:2a15:3767:358f:480e:202d:1234', NOW(), 'michael-e', 1, 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/602.2.14 (KHTML, like Gecko) Version/10.0.1 Safari/602.2.14', 'Anti Brute Force', UUID() )

The issue will not occur if you increase the length of the IP columns (in all four tables) to `VARCHAR 45` (whis is the maximum lenght of an IPv6 address, see <http://stackoverflow.com/a/7477384>).

### PR DESCRIPTION
**Pull request by michael-e**

### CODE REVIEW

**Comment by michael-e** [comment]
BTW, I tested an update and a fresh install alike — both worked as expected IMHO. So if you don't see anything stupid in the code, we should be fine.

**Comment by nitriques** [comment]
Perfect! Thanks!

**Comment by michael-e** [comment]
I can see 2.0.2 on the horizon. :-)

**Comment by nitriques** [comment]
Yup. Done!

**Comment by michael-e** [comment]
Thanks!

**Comment by nitriques** [comment]
Thanks to you!

**Pull request merged**
