### PR TITLE
Rename mistyped function, release 2.0

### PR DESCRIPTION
**Pull request by michael-e**

### CODE REVIEW

**Comment by michael-e** [comment]
Please don't forget to merge dev into master. :-)

**Comment by nitriques** [comment]
Thanks a million times!

**Comment by nitriques** [comment]
[There you go](https://github.com/Solutions-Nitriques/anti_brute_force/releases/tag/2.0.0) :+1:

**Comment by michael-e** [comment]
Cool, thanks!

**Pull request merged**
